services:
  mongodb:
    image: mongo:7
    container_name: chatqa-mongodb
    environment:
      - MONGO_INITDB_DATABASE=chatqa
    ports:
      - "27017:27017"
    volumes:
      - chatqa_mongodb_data:/data/db

volumes:
  chatqa_mongodb_data:
